name: flutterritory
description: MobX

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  flutter_mobx: ^0.3.0+1
  repository:
    path: ../repository
  url_launcher: ^5.1.0

dev_dependencies:
  build_runner: ^1.5.2
  flutter_test:
    sdk: flutter
  mobx_codegen: ^0.3.3+1

flutter:
  uses-material-design: true