name: flutterritory
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_value: ^6.6.0
  built_collection: ^4.2.2

  http: ^0.12.0

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_redux: ^0.5.3

  build_runner: ^1.5.2
  built_value_generator: ^6.6.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true