name: flutterritory
description: Flutterritory - ReduRx

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  redurx: ^1.1.1
  repository:
    path: ../repository
  url_launcher: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true