name: repository
description: Repository - TopStories

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_collection: ^4.2.2
  built_value: ^6.7.0
  http: ^0.12.0+2

dev_dependencies:
  build_runner: ^1.5.2
  built_value_generator: ^6.7.0
  test: ^1.6.5