name: flutterritory
description: Flutterritory - BLoC

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_bloc: ^0.19.1
  cupertino_icons: ^0.1.2
  equatable: ^0.3.0
  flutter:
    sdk: flutter
  rxdart: ^0.22.0
  repository:
    path: ../repository
  url_launcher: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true