name: flutterritory
description: Flutterritory - Build Redux

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  built_redux: ^7.5.4
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  repository:
    path: ../repository
  url_launcher: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true